name = "HashCode2019Final"
uuid = "53baf983-67ec-4d57-bcf2-42415a9f90bc"
authors = ["Guillaume Dalle"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
